### ISSUE TITLE
Opinions on the API naming/structure

### ISSUE THREAD

**Issue by gabek** [gabek/GitYourFeedback#14]
Anybody have any API suggestions before it gets locked in?  Currently there's a `FeedbackManagerDatasource` protocol that has

`func uploadUrl(_ completionHandler: (String) -> Void)`
`func additionalData() -> String?`

The init for FeedbackManager is
`init(githubApiToken: String, githubUser: String, repo: String, feedbackRemoteStorageDelegate: FeedbackManagerDatasource, issueLabels: [String]?)`

And to manually display the feedback interface it's
`feedbackManager.display()` with an optional view controller to display it from.

Is this clear and optimal?

**Comment by funky-monkey** [comment]
I'd like to pick this up for #hacktoberfest.

What i've done now is changed the init a bit so it takes a FeedbackOptions protocol so you are not bound to use github as a repo and can create concrete implementations for any type of repo. I have some more ideas, shall i open a PR?

Kind regards, 
Sidney

**Comment by gabek** [comment]
@funky-monkey This sounds fantastic, I'd love to see what you've got!  I always hoped for expanding this.  Same goes for uploading screenshots, limiting it to Google doesn't make much sense... but was a starting point.

We could always have two initializers.  One that takes a simple implementation using Github Issues for feedback storage, and another that is completely customizable using the FeedbackOptions protocol.

**Comment by gabek** [comment]
Added sanity by moving the labels to the datasource protocol.  Documented the change:

https://github.com/gabek/GitYourFeedback/commit/29c76d6e03095053f23d014b5ac3c061c6aa4ec4

**Comment by gabek** [comment]
@funky-monkey I'm going to close this down for now unless you have a PR you'd like to put up with your FeedbackOptions protocol.  If not now, I'd love to still check it out for a future revision.

**Comment by funky-monkey** [comment]
YES! Picking this up this weekend - hold on a little longer ;-)

**Comment by gabek** [comment]
Re-opening since @funky-monkey is on this.
