### ISSUE TITLE
Tapping the screenshot button should give options of what to do with the image

### ISSUE THREAD

**Issue by gabek** [gabek/GitYourFeedback#16]
If a screenshot is attached tapping the button should give users options of what to do:
- [ ] Remove screenshot
  -  Removes the screenshot from the issue and reverts the button back to an empty state (#15)
- [ ] Replace screenshot
  -  Allow the user to select a different image from their library
- [ ] View screenshot
  - Display the image full screen.

**Comment by nagashayan** [comment]
Am working on this
