### ISSUE TITLE
Replace icons with nicer ones for all resolutions

### ISSUE THREAD

**Issue by gabek** [gabek/GitYourFeedback#26]
Right now we have three icons for add, close and save.  They are a single resolution, and they don't look great as they don't have a style that matches.  Plus I stole them from Google images.

These are the three icons:

https://github.com/gabek/GitYourFeedback/tree/master/GitYourFeedback/Assets

If anybody has any resources or artistic skills feel free to reply with any suggestions and then a PR can be created to replace them.

**Comment by qbunt** [comment]
@gabek could these be SVG?

**Comment by gabek** [comment]
@qbunt Good question, but sadly no.  They need to be supported natively by iOS and the asset catalog.  But PDF is a good option since one size can be provided and all of the resolutions will be generated at build time.

Here's a good overview on using PDFs with image sets.  https://icons8.com/articles/how-to-use-vectors-in-xcode-7/

**Comment by noahfeder** [comment]
@gabek I'd be happy to get you the appropriate icon set based on Google's material design. Three sizes per icon?

**Comment by gabek** [comment]
@noahfeder Awesome!  Three sizes (The base size, @2x, and @3x).  The alternative is one image that's a PDF and Xcode creates the three images at build time.  It's a handy alternative.

While I think Google's material design looks great, it is very Android distinctive.  iOS icons are often a little thinner and less often filled in.  I found a nice comparison here: https://blog.dropsource.com/whats-different-when-designing-apps-for-ios-or-android-99648738206b#.kmnb3gtgb (scroll to the `Icons` section).

Are you able to get the project up and running to test the new icons and see how they look?  I'm happy to help.

**Comment by noahfeder** [comment]
Sorry for the slow response. I'm new-ish to XCode, having only really used it for a React Native project, so this error is throwing me for a loop when I try to build/run the Example app.

`Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.`

**Comment by gabek** [comment]
@noahfeder Oh no!  Hopefully we can figure this out.

Make sure you're on Xcode 8.0, as that has the implementation of Swift 3 that we require to run the project.

Are you able to `pod install` from the `Example` directory?

**Comment by gabek** [comment]
Thanks for taking care of this, @funky-monkey!
