### ISSUE TITLE
Easy!: Create animated GIF of the project in use

### ISSUE THREAD

**Issue by gabek** [gabek/GitYourFeedback#40]
- Add this to a project of yours, or if you have nothing to add it to, use the example project.
- Use something like [Licecap](http://www.cockos.com/licecap/) to create an animated GIF of you using it.
- Create a PR adding the file to the repo.  Feel free to add it to the web site (docs folder) or the Readme as well.

**Comment by cglewis** [comment]
I'll look into trying to make one for this, does this work on iOS only?

**Comment by gabek** [comment]
@cglewis: Yup, iOS only.

**Comment by cglewis** [comment]
Ah, scratch that then.

**Comment by satiewaltz** [comment]
Working on this, will make a PR in a bit.

**Comment by gabek** [comment]
Closed in favor of #23.
