### ISSUE TITLE
Before release: Add to cocoapods

### ISSUE THREAD

**Issue by gabek** [gabek/GitYourFeedback#5]
https://guides.cocoapods.org/making/making-a-cocoapod.html#release

**Comment by OlliePoole** [comment]
I can help with this, it's relatively straight forward.

**Comment by gabek** [comment]
Thanks for offering, @OlliePoole!  I'm still working on the v0.1.0, so it's not ready to be released yet.  Feel free to help push to that milestone!  #8 and #9 dealing with error handling are still todos.

I've never used Carthage before, so if you want to add instructions to the Readme on how to install via Carthage that's needed as well.  That's filed in #6.
