### ISSUE TITLE
Adapt to work with  Swift 2.3 & minimum iOS 8

### ISSUE THREAD

**Issue by fredfalcon** [gabek/GitYourFeedback#53]

**Comment by gabek** [comment]
Hi @seanauriti,

While I can appreciate the need for this, Swift 2.3 is not long for this world as Xcode 8.2 will be the last version to support it.

And while I could be convinced that supporting iOS 9 might be worthwhile to some people, [iOS 8 isn't much on the radar anymore](https://mixpanel.com/trends/#report/ios_10).

**Comment by fredfalcon** [comment]
@gabek ok thanks for letting me know.  I need this for a project so I'd be willing to put a bounty on www.coderbounty.com - how long do you think it would take to code the change?

**Comment by gabek** [comment]
@seanauriti I imagine if you're talking iOS 9 It wouldn't be more than a few hours of work.  I'm having a hard time thinking of anything specific to iOS 10 that's being used, but I'm probably just forgetting.  To support iOS 8 the UI would have to be rebuilt without using UIStackView.
