### ISSUE TITLE
Fix crash on launch for demo project (iOS 11)

### ISSUE THREAD

**Issue by gabek** [gabek/GitYourFeedback#56]

**Comment by macbellingrath** [comment]
I am unable to produce a crash on launch running Demo scheme with iPhone X sim/iOS 11. 
Can you provide any more information relating to the crash?

**Comment by dylanmaryk** [comment]
I'm also unable to produce the crash, on an iPhone 8 simulator running iOS 11.

**Comment by gabek** [comment]
Awesome, thanks for testing!
