### ISSUE TITLE
Update to Swift 4.x

### ISSUE THREAD

**Issue by gabek** [gabek/GitYourFeedback#57]

**Comment by damien-rivet** [comment]
Hi @gabek,

I'll be working on upgrading to `Swift 4+`, expect a PR soon.

**Comment by pchelnikov** [comment]
@Ethenyl sorry but it's already done

**Comment by damien-rivet** [comment]
@pchelnikov my bad then ;-)

**Comment by damien-rivet** [comment]
@gabek could you close the ticket so it won't happen again. Thanks.
