### ISSUE TITLE
Error handling: Failed upload to storage

### ISSUE THREAD

**Issue by gabek** [gabek/GitYourFeedback#8]
This should bubble up an error in some way. Probably a simple popup stating that the upload could not complete, but the feedback was still sent successfully, just without a screenshot.

**Comment by BNTR** [comment]
Hi!) I looked through this task and I have a question. I tried show alert on FeedbackInterfaceViewController, but if we allow to send feedback without screenshot, after success uploading method 'close' called which dismiss FeedbackInterfaceViewController. What behavior should be when we present alert on FeedbackInterfaceViewController, but 'close' (with dismiss(animated: true, completion: nil)) called ? Should we hide alert and VC, or do it only when user tap on 'OK' button?

**Comment by gabek** [comment]
Good question! I think we should keep the VC around until we know if the issue saved properly.  So if the screenshot upload failed, but the issue creation was successful, we can then close the VC and show the popup alerting the user that the issue was created, but the screenshot didn't get sent along with it.

Would that make sense?
